// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {LibNum} from "./lib/LibNum.sol";

/*───────────────────────────────────────────────────────────────────────────
  Chrome — the parts of the site that are the same on every page

  Five contracts render pages, and EIP-170 is why there are five rather than
  one. Left to themselves each would carry its own copy of the stylesheet
  and its own copy of the wallet client, which wastes the bytes twice over:
  once in code size, and once when the copies drift and the site stops
  looking like one site. So the shell lives here and the pages call it.

  ── the client, and why it is forty lines ──

  A storefront that cannot transact is a brochure. These pages have to be
  able to hand a visitor's wallet a transaction, which normally means
  shipping an ABI coder and a keccak-256 to compute a selector.

  It does not mean that here, because the page is generated by a contract.
  Solidity has keccak. Every selector, and every argument the *page* knows,
  is encoded on chain and arrives as a finished calldata prefix; the browser
  appends the words the visitor typed and nothing else. What is left is
  hex-padding and `eth_sendTransaction`.

  That is not only smaller, it is the same argument the rest of this
  collection makes: a client that computes less is a client that can be
  wrong about less. A visitor can read `data-call` in the page source and
  compare it to the contract themselves — the selector is right there, in a
  document the chain produced.

  Providers are found by EIP-6963 with `window.ethereum` as the fallback,
  and the chain id is written into the page at render time so a wallet
  pointed somewhere else is told so instead of quietly sending a
  transaction to the wrong network.
───────────────────────────────────────────────────────────────────────────*/
contract Chrome {
    using LibNum for uint256;

    /*═══════════════════ the shell ═══════════════════*/

    function head(string memory title) external pure returns (string memory) {
        return string.concat(
            "<!doctype html><meta charset=utf-8>"
            "<meta name=viewport content=\"width=device-width,initial-scale=1\">"
            "<title>", title, "</title><style>", CSS, "</style>"
        );
    }

    string internal constant CSS =
        ":root{color-scheme:dark}"
        "body{background:#07080c;color:#c9d3e6;font:15px/1.65 ui-sans-serif,system-ui,sans-serif;"
        "max-width:62rem;margin:0 auto;padding:2.2rem 1.5rem 6rem}"
        "h1{font-weight:500;letter-spacing:.22em;font-size:1.5rem;margin:0 0 .3rem}"
        "h2{font-weight:500;letter-spacing:.14em;font-size:.8rem;text-transform:uppercase;"
        "color:#8b95ad;margin:2.6rem 0 .8rem}"
        "h3{font-weight:500;font-size:1rem;margin:1.6rem 0 .4rem;color:#dbe4f5}"
        "a{color:#7fd4ff}.b{text-decoration:none;color:#8b95ad}"
        ".g{display:inline-block;border:1px solid #2a3550;border-radius:.4rem;"
        "padding:.5rem .9rem;text-decoration:none;margin:0 .4rem .6rem 0}"
        ".e{color:#8b95ad;font-size:.92rem}"
        ".w{color:#ffb27f}.ok{color:#7fe0a8}.no{color:#ff8a8a}"
        "code{font:12.5px ui-monospace,monospace;color:#9fb0cc;overflow-wrap:anywhere}"
        "dl{display:grid;grid-template-columns:9.5rem 1fr;gap:.35rem 1rem;margin:1.4rem 0}"
        "dt{color:#6c7689;font-size:.82rem;letter-spacing:.1em;text-transform:uppercase}"
        "dd{margin:0}"
        "ul.r{list-style:none;padding:0;display:grid;"
        "grid-template-columns:repeat(auto-fill,minmax(11rem,1fr));gap:.5rem}"
        "ul.r li{border:1px solid #1a2030;border-radius:.4rem;padding:.6rem .8rem}"
        ".m{color:#6c7689;font-size:.8rem;display:block}"
        "iframe,img{width:100%;max-width:38rem;aspect-ratio:1;border:1px solid #1a2030;"
        "border-radius:.5rem;background:#000;display:block}"
        "nav{display:flex;flex-wrap:wrap;gap:.3rem;margin:.2rem 0 1.8rem;"
        "border-bottom:1px solid #161c2a;padding-bottom:1rem}"
        "nav a{font-size:.82rem;letter-spacing:.08em;text-transform:uppercase;"
        "text-decoration:none;color:#8b95ad;padding:.32rem .6rem;border-radius:.3rem}"
        "nav a.on{background:#141a28;color:#cfe3ff}"
        ".card{border:1px solid #1a2030;border-radius:.55rem;padding:1.1rem 1.2rem;margin:.9rem 0}"
        ".card h3{margin-top:0}"
        "table{border-collapse:collapse;width:100%;font-size:.9rem;margin:1rem 0}"
        "th{text-align:left;color:#6c7689;font-weight:500;font-size:.78rem;"
        "letter-spacing:.1em;text-transform:uppercase;padding:.4rem .6rem .4rem 0}"
        "td{padding:.4rem .6rem .4rem 0;border-top:1px solid #141a28}"
        "input{background:#0c0f16;border:1px solid #232c42;border-radius:.35rem;color:#dbe4f5;"
        "font:13px ui-monospace,monospace;padding:.45rem .6rem;width:100%;max-width:22rem}"
        "label{display:block;color:#6c7689;font-size:.78rem;letter-spacing:.08em;"
        "text-transform:uppercase;margin:.7rem 0 .25rem}"
        "button{background:#16203a;border:1px solid #2a3550;border-radius:.4rem;color:#cfe3ff;"
        "font:13px ui-sans-serif,system-ui,sans-serif;padding:.5rem .95rem;cursor:pointer;"
        "margin:.8rem .4rem 0 0}"
        "button:hover{background:#1d2a4a}"
        "#s{margin-top:.9rem;font:12.5px ui-monospace,monospace;color:#8b95ad;"
        "overflow-wrap:anywhere;min-height:1.2em}";

    /*═══════════════════ navigation ═══════════════════*/

    /// @dev `here` is an index into the same order the links are written in,
    ///      so the current page is not a link to itself. 255 means none.
    function nav(uint256 id, uint8 here) external pure returns (string memory) {
        string memory t = id.str();
        return string.concat(
            "<nav>",
            _tab("/", "index", here == 0),
            _tab(string.concat("/token/", t), "token", here == 1),
            _tab(string.concat("/token/", t, "/live"), "instrument", here == 2),
            _tab(string.concat("/token/", t, "/market"), "market", here == 3),
            _tab(string.concat("/token/", t, "/rent"), "rent", here == 4),
            _tab(string.concat("/token/", t, "/vault"), "vault", here == 5),
            _tab(string.concat("/token/", t, "/services.json"), "json", here == 6),
            "</nav>"
        );
    }

    function navTop(uint8 here) external pure returns (string memory) {
        return string.concat(
            "<nav>",
            _tab("/", "index", here == 0),
            _tab("/open", "open markets", here == 7),
            _tab("/services.json", "json", here == 6),
            "</nav>"
        );
    }

    function _tab(string memory href, string memory label, bool on)
        private pure returns (string memory)
    {
        return string.concat(
            "<a", on ? " class=on" : "", " href=\"", href, "\">", label, "</a>"
        );
    }

    /*═══════════════════ the footer, and the client ═══════════════════*/

    function foot(address premises, uint256 chainId) external pure returns (string memory) {
        return string.concat(
            "<h2>about this page</h2>"
            "<p class=e>An ERC-5219 contract at <code>", LibNum.hexAddr(premises),
            "</code> on chain <code>", chainId.str(),
            "</code>, reached over <code>web3://</code> with no DNS and no server. "
            "It holds none of the artwork: every token renders identically whether "
            "this contract exists, is abandoned, or is replaced. Every transaction "
            "offered here is built on chain &mdash; the selector in each "
            "<code>data-call</code> came out of a contract, not out of this page's "
            "JavaScript, and you can check it against the ABI yourself.</p>"
            "<div id=s></div>",
            script(chainId)
        );
    }

    /// @notice The whole client. It pads numbers, appends them to calldata a
    ///         contract already built, and sends. It does not encode
    ///         selectors, because it does not have to.
    function script(uint256 chainId) public pure returns (string memory) {
        return string.concat(
            "<script>(()=>{",
            "const W=", chainId.str(), ";",
            "const P=[];addEventListener('eip6963:announceProvider',e=>P.push(e.detail));",
            "dispatchEvent(new Event('eip6963:requestProvider'));",
            "const pv=()=>(P[0]&&P[0].provider)||window.ethereum;",
            "const who=()=>(P[0]&&P[0].info&&P[0].info.name)||'the injected provider';",
            "const S=document.getElementById('s');",
            "const say=(m,c)=>{S.textContent=m;S.className=c||''};",
            "let A=null;",
            // 32-byte word from a decimal string, a 0x string, or an address
            // padStart never truncates, so an over-long value would have
            // produced calldata that is not 4+32n and been silently
            // misread by the contract as different arguments entirely.
            "const pad=h=>{h=h.replace(/^0[xX]/,'').toLowerCase();",
            "if(!/^[0-9a-f]*$/.test(h))throw new Error('not a number: 0x'+h);",
            "if(h.length>64)throw new Error('value does not fit in a word');",
            "return h.padStart(64,'0')};",
            "const W256=v=>{v=String(v==null?'':v).trim()||'0';",
            "return pad(/^0[xX]/.test(v)?v:BigInt(v).toString(16))};",
            "const AD=v=>{v=String(v==null?'':v).trim();",
            "if(!/^0x[0-9a-fA-F]{40}$/.test(v))throw new Error('not an address: '+v);return pad(v)};",
            "const val=id=>{const e=document.getElementById(id);return e?e.value:''};",
            "const build=el=>{let d=el.dataset.call;",
            "for(const f of (el.dataset.args||'').split(',').filter(Boolean)){",
            "const p=f.split(':'),k=p[1],raw=p[0]==='@'?A:val(p[0]);",
            "d+=k==='addr'?AD(raw||A):k==='bool'?W256(/^(1|true|yes)$/i.test(String(raw))?1:0):W256(raw)}",
            "return d};",
            "const conn=async()=>{const p=pv();if(!p)throw new Error('no wallet found');",
            "const a=await p.request({method:'eth_requestAccounts'});A=a[0];",
            "const c=await p.request({method:'eth_chainId'});",
            "if(BigInt(c)!==BigInt(W))throw new Error('wallet is on chain '+BigInt(c)+', this page is chain '+W);",
            "say('using '+who());return p};",
            "document.querySelectorAll('[data-call]').forEach(el=>el.addEventListener('click',async()=>{",
            "try{say('...');",
            // a read on the wrong chain is a number from the wrong chain,
            // and the number is what the visitor decides the trade on
            "if(el.dataset.read!==undefined){const p=pv();if(!p)throw new Error('no wallet found');",
            "const cc=await p.request({method:'eth_chainId'});",
            "if(BigInt(cc)!==BigInt(W))throw new Error('wallet is on chain '+BigInt(cc)+', this page is chain '+W);",
            "const r=await p.request({method:'eth_call',params:[{to:el.dataset.to,data:build(el)},'latest']});",
            "if(!r||r.length<66)throw new Error('the call returned nothing');",
            "const o=el.dataset.out&&document.getElementById(el.dataset.out);",
            "const n=BigInt('0x'+r.slice(2,66));",
            "if(o)o.textContent=n.toString();say('read '+n,'ok');return}",
            "const p=await conn();",
            "const tx={from:A,to:el.dataset.to,data:build(el)};",
            "const v=el.dataset.value!==undefined?(el.dataset.valfrom?val(el.dataset.valfrom):el.dataset.value):null;",
            "if(v!==null)tx.value='0x'+BigInt(v).toString(16);",
            "const h=await p.request({method:'eth_sendTransaction',params:[tx]});",
            "say('sent '+h,'ok')}",
            "catch(e){say(String(e&&e.message||e),'no')}",
            "}));",
            "})()</script>"
        );
    }
}
