// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {LibNum} from "./lib/LibNum.sol";
import {Web} from "./lib/Web.sol";
import {IHub, IPoolRead, ILeaseRead, IRendererDoc, IParley, IVenue, MarketView}
    from "./interfaces/Site.sol";

/*───────────────────────────────────────────────────────────────────────────
  PageManifest — the same shopfront, for something that cannot read a page

  A website whose services can only be used by a person clicking is half a
  website. Most of what will ever want to trade against four thousand
  independent markets, or rent an instrument for an afternoon, is not a
  person: it is a script, a bot, an agent. Those need the same three facts a
  human needs — what is on offer, what it costs, and exactly how to ask —
  and they need them without a hosted API, an indexer, a subgraph or a
  documentation site, because every one of those is a dependency that can be
  taken away and the token cannot.

  So the manifest is generated by the same contract that generates the page,
  from the same reads, in the same block. It cannot drift from what the site
  says because it is not a second source of truth; it is the same one,
  serialised differently.

  Each service carries its selector, not only its signature. A caller that
  has the selector does not need a keccak implementation, an ABI file, or
  this contract's continued existence — it needs an RPC endpoint. That is
  the smallest a dependency gets.

  ── this is not an ERC ──

  There is no standard for "what services does this NFT offer". This is a
  plain JSON object with an explicit `"schema"` string, served under a
  stable path, and it makes no claim beyond that. If a standard arrives,
  serving it too is another route on a contract that already has one for
  every other thing here.
───────────────────────────────────────────────────────────────────────────*/
contract PageManifest {
    using LibNum for uint256;

    IHub       public immutable HUB;
    IPoolRead  public immutable POOL;
    ILeaseRead public immutable LEASE;
    /// @dev May be the zero address: a chain with no Uniswap deployment has
    ///      no venue, and the manifest says so rather than omitting the key
    ///      — an absent key and a present-but-empty one mean different
    ///      things to a program, and only one of them is the truth.
    IParley    public immutable PARLEY;
    address    public immutable KILN;
    address    public immutable LOCKER;
    IVenue     public immutable VENUE;

    string public constant SCHEMA = "ipseity.services/1";

    /// @dev Same window as the directory page, same reason.
    uint256 public constant PAGE = 24;

    constructor(IHub hub, IPoolRead pool, ILeaseRead lease, IParley parley,
                address kiln, address locker, IVenue venue) {
        KILN = kiln;
        LOCKER = locker;
        VENUE = venue;
        HUB = hub;
        POOL = pool;
        LEASE = lease;
        PARLEY = parley;
    }

    /*═══════════════════ /token/<id>/services.json ═══════════════════*/

    function token(uint256 id) external view returns (string memory) {
        /*  Joined rather than concatenated with the separators baked into
            each entry. Every service here is conditional on something —
            a pool being wired, a renderer answering, an account being
            deployed — and an entry that returns "" while the next one
            begins with a comma is a document that is no longer JSON. The
            separator belongs to the list, not to the items.            */
        string[5] memory parts = [_trade(id), _rent(id), _give(id), _draw(), _verify(id)];
        string memory body;
        for (uint256 i; i < 5; ++i) {
            if (bytes(parts[i]).length == 0) continue;
            body = bytes(body).length == 0 ? parts[i] : string.concat(body, ",", parts[i]);
        }
        return string.concat(_who(id), "\",\"services\":[", body, "]}");
    }

    function _who(uint256 id) private view returns (string memory) {
        return string.concat(
            "{\"schema\":\"", SCHEMA,
            "\",\"chainId\":", block.chainid.str(),
            ",\"collection\":\"", LibNum.hexAddr(address(HUB)),
            "\",\"token\":", id.str(),
            ",\"holder\":\"", LibNum.hexAddr(HUB.ownerOf(id)),
            "\",\"operator\":\"", LibNum.hexAddr(_operator(id)),
            "\",\"bound\":", HUB.locked(id) ? "true" : "false",
            ",\"word\":\"", HUB.sectionOf(id).str(),
            "\",\"reach\":\"", LibNum.hexAddr(HUB.account(id)),
            "\",\"grip\":\"", LibNum.hexAddr(HUB.grip(id))
        );
    }

    function _operator(uint256 id) private view returns (address a) {
        a = HUB.userOf(id);
        if (a == address(0)) a = HUB.ownerOf(id);
    }

    /*═══════════════════ one entry per service ═══════════════════*/

    function _trade(uint256 id) private view returns (string memory) {
        if (address(POOL) == address(0)) return "";
        MarketView memory m;
        (
            m.base, m.quote, m.rBase, m.rQuote, m.feeBps, m.open,
            m.conc, m.spot, m.maxBaseOut, m.maxQuoteOut, m.trades, m.bondUntil
        ) = POOL.market(id);

        if (!m.open) {
            return string.concat(
                "{\"id\":\"trade\",\"open\":false,\"contract\":\"",
                LibNum.hexAddr(address(POOL)),
                "\",\"why\":\"this token has not opened a market\"}"
            );
        }
        return string.concat(
            "{\"id\":\"trade\",\"open\":", POOL.paused() ? "false" : "true",
            ",\"paidTo\":\"token\",\"contract\":\"", LibNum.hexAddr(address(POOL)),
            "\",\"base\":", _asset(m.base),
            ",\"quote\":", _asset(m.quote),
            ",\"reserves\":[\"", uint256(m.rBase).str(), "\",\"", uint256(m.rQuote).str(),
            "\"],\"feeBps\":", uint256(m.feeBps).str(),
            _tradeTail(id, m)
        );
    }

    function _tradeTail(uint256 id, MarketView memory m) private pure returns (string memory) {
        return string.concat(
            ",\"spotQuotePerBase\":\"", m.spot.str(),
            "\",\"concentrationBps\":", m.conc.str(),
            ",\"maxOut\":[\"", m.maxBaseOut.str(), "\",\"", m.maxQuoteOut.str(),
            "\"],\"trades\":", m.trades.str(),
            ",\"bondedUntil\":", uint256(m.bondUntil).str(),
            /*  Not "quote". This object already has a `quote` key holding
                the quote *asset*, and a duplicate key is legal JSON that
                every parser resolves by keeping the last one — so naming
                the pricing call `quote` silently deleted the address,
                symbol and decimals of the token being priced. The
                machine-readable layer is the one place a collision like
                that is invisible until something acts on it.          */
            ",\"quoteCall\":", _call("quote(uint256,bool,uint256)", "view"),
            ",\"invoke\":", _call("swap(uint256,bool,uint256,uint256,address,uint256)", "send"),
            ",\"firstArg\":", id.str(),
            ",\"note\":\"approve the pool for the token you are sending; the pool credits "
            "only what arrives, so fee-on-transfer tokens are charged honestly\"}"
        );
    }

    function _rent(uint256 id) private view returns (string memory) {
        if (address(LEASE) == address(0)) return "";
        (
            bool ok, uint8 reason,
            uint128 perDay, uint32 minD, uint32 maxD,
            address renter, uint64 until,
            uint256 vested,
        ) = LEASE.listing(id);

        return string.concat(
            "{\"id\":\"rent\",\"open\":", ok ? "true" : "false",
            ",\"paidTo\":\"token\",\"contract\":\"", LibNum.hexAddr(address(LEASE)),
            "\",\"why\":\"", _why(reason),
            "\",\"perDayWei\":\"", uint256(perDay).str(),
            "\",\"minDays\":", uint256(minD).str(),
            ",\"maxDays\":", uint256(maxD).str(),
            ",\"renter\":\"", LibNum.hexAddr(renter),
            "\",\"until\":", uint256(until).str(),
            ",\"vestedWei\":\"", vested.str(),
            "\",\"invoke\":", _call("rent(uint256,uint32,uint128)", "send"),
            ",\"firstArg\":", id.str(),
            ",\"value\":\"perDayWei * days, exactly\""
            ",\"grants\":\"ERC-4907 user: may commit orientations and set writable traits; "
            "may never transfer, approve, lock or reach either vault\"}"
        );
    }

    function _why(uint8 reason) private pure returns (string memory) {
        if (reason == 0) return "available";
        if (reason == 1) return "the holder has published no terms";
        if (reason == 2) return "the token has not named this contract its lease agent";
        return "already let";
    }

    function _give(uint256 id) private view returns (string memory) {
        return string.concat(
            "{\"id\":\"give\",\"open\":true,\"paidTo\":\"token\",\"contract\":\"",
            LibNum.hexAddr(HUB.grip(id)),
            "\",\"invoke\":{\"kind\":\"transfer\",\"data\":\"0x\"}"
            ",\"oneWay\":true"
            ",\"note\":\"the bytecode at this address contains no path that moves value "
            "out; ERC-20 and ERC-721 transfers to it are equally permanent\"}"
        );
    }

    function _draw() private view returns (string memory) {
        address sigil;
        address r = HUB.renderer();
        if (r != address(0)) {
            (bool ok, bytes memory out) =
                r.staticcall(abi.encodeWithSelector(IRendererDoc.sigil.selector));
            if (ok && out.length >= 32) sigil = abi.decode(out, (address));
        }
        if (sigil == address(0)) return "";
        return string.concat(
            "{\"id\":\"draw\",\"open\":true,\"paidTo\":null,\"contract\":\"",
            LibNum.hexAddr(sigil),
            "\",\"read\":", _call("pathAlong(uint256,bytes32,uint8)", "view"),
            ",\"also\":", _call("quartet(uint256,uint256,bytes32)", "view"),
            ",\"note\":\"free and unguarded: it does not check the caller and does not "
            "check that the word belongs to any token\"}"
        );
    }

    function _verify(uint256 id) private view returns (string memory) {
        address reach = HUB.account(id);
        return string.concat(
            "{\"id\":\"verify\",\"open\":", reach.code.length > 0 ? "true" : "false",
            ",\"paidTo\":null,\"contract\":\"", LibNum.hexAddr(reach),
            "\",\"read\":", _call("isValidSignature(bytes32,bytes)", "view"),
            ",\"magic\":\"0x1626ba7e\""
            ",\"note\":\"validates only digests rebuildable under this account's own "
            "EIP-712 attestation domain; every other digest is refused, including one the "
            "holder signed correctly\"}"
        );
    }

    /*═══════════════════ /services.json ═══════════════════*/

    /// @notice The collection, and a window of tokens with something on
    ///         offer. Paged for the same reason the directory page is.
    function index(uint256 page) external view returns (string memory) {
        uint256 supply = HUB.totalSupply();
        uint256 from = page * PAGE + 1;
        uint256 to = from + PAGE - 1;
        if (to > supply) to = supply;

        string memory rows;
        bool first = true;
        for (uint256 id = from; id <= to && id <= supply; ++id) {
            bool marketOpen;
            bool rentable;
            if (address(POOL) != address(0)) (,,,,, marketOpen,,,,,,) = POOL.market(id);
            if (address(LEASE) != address(0)) (rentable,,,,,,,,) = LEASE.listing(id);
            if (!marketOpen && !rentable) continue;
            rows = string.concat(
                rows, first ? "" : ",",
                "{\"token\":", id.str(),
                ",\"trade\":", marketOpen ? "true" : "false",
                ",\"rent\":", rentable ? "true" : "false",
                ",\"manifest\":\"/token/", id.str(), "/services.json\"}"
            );
            first = false;
        }

        return string.concat(
            _collection(supply),
            ",\"window\":{\"from\":", from.str(), ",\"to\":", to.str(),
            ",\"pageSize\":", PAGE.str(), ",\"page\":", page.str(),
            ",\"more\":", to < supply ? "true" : "false",
            ",\"next\":\"/services.json/", (page + 1).str(), "\"}",
            ",\"offering\":[", rows, "]}"
        );
    }

    function _collection(uint256 supply) private view returns (string memory) {
        return string.concat(
            "{\"schema\":\"", SCHEMA,
            "\",\"chainId\":", block.chainid.str(),
            ",\"collection\":\"", LibNum.hexAddr(address(HUB)),
            "\",\"issued\":", supply.str(),
            ",\"ceiling\":", HUB.MAX_SUPPLY().str(),
            /*  The edition is split into contiguous bands, one per chain,
                fixed at deployment. A program reading only `ceiling` would
                conclude this chain is the whole collection.            */
            ",\"band\":{\"first\":", HUB.FIRST_ID().str(),
            ",\"last\":", HUB.LAST_ID().str(),
            ",\"collection\":", HUB.COLLECTION().str(), "}",
            /*  And where the rest of the edition is issued from. Without
                this a program can learn which numbers THIS chain owns and
                has no way to discover that the other three thousand exist
                somewhere — it would read one band as the whole collection
                and be wrong by a factor of four. Static, because the
                partition is fixed at deployment on every chain and a
                lookup that could disagree between chains would be worse
                than no lookup at all.                                  */
            ",\"edition\":", EDITION,
            ",\"mintPriceWei\":\"", HUB.price().str(),
            "\",\"pool\":\"", LibNum.hexAddr(address(POOL)),
            "\",\"lease\":\"", LibNum.hexAddr(address(LEASE)),
            /*  This used to end mid-value — the caller supplied the closing
                quote of the lease address, which meant the two could not be
                read apart and appending anything here broke the document
                silently. It terminates its own values now.              */
            "\",\"routes\":", ROUTES,
            ",\"parley\":", _parley(),
            /*  The two contracts a program would want to drive without the
                pages: the kiln launches, the locker keeps. Addresses only —
                their ABIs are in the repository and their selectors on the
                pages that call them.                                     */
            ",\"kiln\":\"", LibNum.hexAddr(KILN),
            "\",\"locker\":\"", LibNum.hexAddr(LOCKER),
            "\",\"venue\":", _venue()
        );
    }

    /*  The routes that are not about one token.

        Without these a program reading this manifest would conclude the
        site was a token directory and nothing else — it lists what each
        token offers and would say nothing about the place they all talk.
        An index that is silently partial is worse than one that is
        obviously small.                                                 */
    /*  The partition, as it is written in tools/site.mjs, which is the one
        table the deploy reads. The suite checks these two against each
        other on every run: a constant that has drifted from the table
        that built the collection would publish a map to the wrong place.

        Chain ids rather than names, because a chain's number is the one
        name it cannot lose.                                             */
    string internal constant EDITION =
        "["
        "{\"chainId\":1,\"name\":\"Ethereum\",\"first\":1,\"last\":1024},"
        "{\"chainId\":8453,\"name\":\"Base\",\"first\":1025,\"last\":2048},"
        "{\"chainId\":130,\"name\":\"Unichain\",\"first\":2049,\"last\":3072},"
        "{\"chainId\":56,\"name\":\"BNB\",\"first\":3073,\"last\":3584},"
        "{\"chainId\":4663,\"name\":\"Robinhood\",\"first\":3585,\"last\":4096}"
        "]";

    string internal constant ROUTES =
        "["
        "{\"path\":\"/\",\"is\":\"the instrument itself, live \\u2014 the token is the interface\"},"
        "{\"path\":\"/door\",\"is\":\"the flat front page: what you hold, the chains, the roll\"},"
        "{\"path\":\"/terminal\",\"is\":\"every function, one line at a time; "
        "window.TERM.run() for agents\"},"
        "{\"path\":\"/chat\",\"is\":\"the commons: one room, every token\"},"
        "{\"path\":\"/rooms\",\"is\":\"the groups a token has entered\"},"
        "{\"path\":\"/room/<n>\",\"is\":\"one group, numbered from 1\"},"
        "{\"path\":\"/dm/<id>\",\"is\":\"the room two tokens share, derived not founded\"},"
        "{\"path\":\"/swap\",\"is\":\"any ERC-20 with a pool, against this "
        "chain's Uniswap v3\"},"
        "{\"path\":\"/gallery\",\"is\":\"the collection, wearing its stills\",\"paged\":true},"
        "{\"path\":\"/launch\",\"is\":\"a v4 launchpad: fixed-supply token, "
        "mined hook, pool\"},"
        "{\"path\":\"/hook/<address>\",\"is\":\"what a hook's address already "
        "says, with no call\"},"
        "{\"path\":\"/lock\",\"is\":\"the vault: tokens in, a date, no early "
        "exit \u2014 ten years on a slider\"},"
        "{\"path\":\"/projector\",\"is\":\"the 4-D renderer, pure and public\"},"
        "{\"path\":\"/name\",\"is\":\"bind an ENS name to a token, ERC-6821 included\"},"
        "{\"path\":\"/keys\",\"is\":\"session keys: scoped, expiring permissions\"},"
        "{\"path\":\"/seal\",\"is\":\"the three seals: soulbind, account, kernel\"},"
        "{\"path\":\"/estate\",\"is\":\"succession \\u2014 a token that outlives its "
        "holder \\u2014 and consignment: escrow with a floor an agent cannot go under\"},"
        "{\"path\":\"/open\",\"is\":\"every open market here\",\"paged\":true},"
        "{\"path\":\"/services.json\",\"is\":\"this document\",\"paged\":true}"
        "]";

    /*  Where the conversation is, and the numbers a program needs to read
        it without this site.

        `said` is the topic0 of the message event and it is the field that
        matters: with it, the contract address and the room key, anything
        that can call `eth_getLogs` can walk the whole archive. This
        manifest is not a convenience for a browser — it is the instruction
        manual for replacing the browser.                                */
    function _parley() private view returns (string memory) {
        if (address(PARLEY) == address(0)) return "null";
        (bytes32 said,,,,) = PARLEY.topics();
        return string.concat(
            "{\"at\":\"", LibNum.hexAddr(address(PARLEY)),
            "\",\"commons\":", PARLEY.COMMONS().str(),
            ",\"groups\":", PARLEY.groups().str(),
            ",\"maxBody\":", PARLEY.MAX_BODY().str(),
            ",\"said\":\"", LibNum.hex32(said),
            "\",\"walk\":\"stateOf(room).last is the block of the newest message; "
            "each message carries the block of the one before it\"}"
        );
    }

    /*  Where those pages send, so a program can check the addresses against
        Uniswap's published deployments rather than against this contract.

        `routerKind` is the field that matters and it is here for the same
        reason it is on the page: two Uniswap routers have an
        `exactInputSingle` whose structs differ by one field, the wrong shape
        does not revert, and a program building calldata from this manifest
        needs to know which one it is talking to. 0 is the v3-periphery
        SwapRouter — eight words, deadline at index 4. 1 is SwapRouter02 —
        seven words, no deadline.                                         */
    function _venue() private view returns (string memory) {
        if (address(VENUE) == address(0)) return "null";
        return string.concat(
            "{\"at\":\"", LibNum.hexAddr(address(VENUE)),
            "\",\"present\":", VENUE.present() ? "true" : "false",
            ",\"factory\":\"", LibNum.hexAddr(VENUE.FACTORY()),
            "\",\"quoter\":\"", LibNum.hexAddr(VENUE.QUOTER()),
            "\",\"router\":\"", LibNum.hexAddr(VENUE.ROUTER()),
            "\",\"routerKind\":", uint256(VENUE.ROUTER_KIND()).str(),
            ",\"positions\":\"", LibNum.hexAddr(VENUE.POSITIONS()),
            "\",\"wrapped\":\"", LibNum.hexAddr(VENUE.WRAPPED()),
            "\",\"governor\":\"", LibNum.hexAddr(VENUE.GOVERNOR()),
            "\",\"govToken\":\"", LibNum.hexAddr(VENUE.GOV_TOKEN()), "\"}"
        );
    }

    /*═══════════════════ shapes ═══════════════════*/

    /// @dev Signature and selector together. A caller holding the selector
    ///      needs neither a keccak nor this contract.
    function _call(string memory sig, string memory kind)
        private pure returns (string memory)
    {
        return string.concat(
            "{\"sig\":\"", sig, "\",\"selector\":\"", _sel(sig), "\",\"kind\":\"", kind, "\"}"
        );
    }

    function _asset(address t) private view returns (string memory) {
        return string.concat(
            "{\"address\":\"", LibNum.hexAddr(t),
            "\",\"symbol\":\"", Web.symbolOfJson(t),
            "\",\"decimals\":", uint256(Web.decimalsOf(t)).str(), "}"
        );
    }

    function _sel(string memory sig) private pure returns (string memory) {
        bytes4 s = bytes4(keccak256(bytes(sig)));
        bytes memory hexd = "0123456789abcdef";
        bytes memory o = new bytes(10);
        o[0] = "0"; o[1] = "x";
        for (uint256 i; i < 4; ++i) {
            o[2 + i * 2] = hexd[uint8(s[i]) >> 4];
            o[3 + i * 2] = hexd[uint8(s[i]) & 0x0f];
        }
        return string(o);
    }
}
